### ISSUE TITLE
Fix Dockerfile user account name.

### ISSUE THREAD

**Issue by kaladay** [TAMULib/CatalogService#186]
I forgot to change the username when I used the iriifservice Dockerfile as a baseline.

Change the username to one more appropriate, such as `catalogservice` or `catalog`.

We should probably standardize the naming scheme.
We may even want to consider going with a generic name rather than the service name to avoid needing this name to be different per docker file.

**Comment by wwelling** [comment]
Added details to https://github.com/TAMULib/CatalogService/issues/184. Closing this to simplify process.
