### ISSUE TITLE
FOLIO implementation of blocks

### ISSUE THREAD

**Issue by jcreel** [TAMULib/CatalogService#89]
"/myrecord/blocks" (credentials)
  GET
  Get blocks for each, Voyager, Illiad, and Ares by NetID.
  Such as: http://XXX/get_voyager_block.php?uin=YYY
---
Unable to size until we determine whether FOLIO will allow patron blocks.

https://dev.folio.org/reference/api/#mod-patron-blocks
https://s3.amazonaws.com/foliodocs/api/mod-patron-blocks/automated-patron-blocks.html

**Comment by wwelling** [comment]
Initial use by MyLibraryService, 
https://github.com/TAMULib/MyLibraryService/blob/master/src/main/java/edu/tamu/app/util/VoyagerUtility.java#L107

Should include the creation of a `Block` Catalog domain POJO. Consider renaming to the most appropriate library semantic.

This may not require a concrete POJO. It is a portion of the response that combines block status from Iliad and Ares.

**Comment by kaladay** [comment]
The tests and the service need to return the appropriate plaintext mimetype instead of application/json.

**Comment by kaladay** [comment]
It is now confirmed that we must support FOLIOs usage of Blocks.
Therefore, this needs to be implemented instead of always returning "false".

**Comment by wwelling** [comment]
Will require lookups of both automated and manual blocks from FOLIO. mod-feefine has the manual blocks.
