### ISSUE TITLE
FOLIO implementation of patron

### ISSUE THREAD

**Issue by jcreel** [TAMULib/CatalogService#90]
"/myrecord/patron" (user)
  GET
  Get patron info, querying patron service.
  Such as: http://XXX/AuthenticatePatronService
  ---
  Consider: /patron/account/{id}
  From: https://s3.amazonaws.com/foliodocs/api/edge-patron/edge-patron.html
  Consider: /patron/account/{id}
  From: https://s3.amazonaws.com/foliodocs/api/edge-patron/mod-patron-patron.html

**Comment by wwelling** [comment]
Initial use by MyLibraryService, 
https://github.com/TAMULib/MyLibraryService/blob/master/src/main/java/edu/tamu/app/util/VoyagerUtility.java#L163

Should include the creation of a `Patron` Catalog domain POJO. Consider renaming to the most appropriate library semantic.

**Comment by kaladay** [comment]
not needed.
