### ISSUE TITLE
FOLIO implementation of fines

### ISSUE THREAD

**Issue by jcreel** [TAMULib/CatalogService#91]
"/myrecord/fines" (user)
  GET
  Get patron info.
  Such as: http://XXX/circulationActions/debt/fines
  ---
  Consider: /patron/account/{id}
  From: https://s3.amazonaws.com/foliodocs/api/edge-patron/edge-patron.html
  (Possibly under "charges").
  Consider: https://s3.amazonaws.com/foliodocs/api/mod-feesfines/feefines.html
  (This is not per user, but if not enough information is not available from the patron endpoint, then this may be needed.)
  Consider: /patron/account/{id}
  From: https://s3.amazonaws.com/foliodocs/api/edge-patron/mod-patron-patron.html

**Comment by wwelling** [comment]
Initial use by MyLibraryService, https://github.com/TAMULib/MyLibraryService/blob/master/src/main/java/edu/tamu/app/util/VoyagerUtility.java#L289

Should include the creation of a `Fine` Catalog domain POJO. Consider renaming to the most appropriate library semantic.

**Comment by wwelling** [comment]
```
curl --location --request GET 'https://edge-modules.folio-test.10.55.148.112.xip.io/patron/account/613001223?apikey=eyJzIjoiY2FmcUpzaVlqTVlTOU80eFlNWTYiLCJ0IjoidGVybiIsInUiOiJlZGdldXNlciJ9&includeLoans=true&includeCharges=true&includeHolds=true'
```
