### ISSUE TITLE
FOLIO implementation of items

### ISSUE THREAD

**Issue by jcreel** [TAMULib/CatalogService#92]
"/myrecord/items" (user)
  GET
  Get (charged) items, with charges and loans.
  This will fetch the holding info by bib id, for each item.
  This will build the libcat url link (or chiron url link for msl), for each item.
  Such as: http://XXX/circulationActions/loans
  ---
  Consider: /patron/account/{id}
  From: https://s3.amazonaws.com/foliodocs/api/edge-patron/edge-patron.html
  (Possibly under "charges" and "loans").
  For BibId replacement, would this be the InstanceId or the ItemId for each item?
  Consider: /circulation/loans
  From: https://s3.amazonaws.com/foliodocs/api/mod-circulation/circulation.html
  (Requires more parameters, but if the patron endpoint above is insufficient this should be sufficient, at least for loans.)
  Consider: /item-storage/items
  From: https://s3.amazonaws.com/foliodocs/api/mod-inventory-storage/item-storage.html
  (Requires more parameters, but if the patron endpoint above is insufficient this should be sufficient.)
  Consider: /patron/account/{id}
  From: https://s3.amazonaws.com/foliodocs/api/edge-patron/mod-patron-patron.html

**Comment by wwelling** [comment]
Initial use by MyLibraryService, https://github.com/TAMULib/MyLibraryService/blob/master/src/main/java/edu/tamu/app/util/VoyagerUtility.java#L350

Should include the creation of a `Loan` Catalog domain POJO. Consider renaming to the most appropriate library semantic.

**Comment by wwelling** [comment]
```
curl --location --request GET 'https://edge-modules.folio-test.10.55.148.112.xip.io/patron/account/613001223?apikey=eyJzIjoiY2FmcUpzaVlqTVlTOU80eFlNWTYiLCJ0IjoidGVybiIsInUiOiJlZGdldXNlciJ9&includeLoans=true&includeCharges=true&includeHolds=true'
```
