### ISSUE TITLE
FOLIO implementation of renewal

### ISSUE THREAD

**Issue by jcreel** [TAMULib/CatalogService#93]
"/myrecord/renew" (in body: href)
  PUT
  Renew a charged item.
  Does a POST to the provided URL.
  Such as: http://XXX/YYY
  ---
  Consider: /patron/account/{id}/item/{itemId}/renew
  From: https://s3.amazonaws.com/foliodocs/api/edge-patron/edge-patron.html
  Consider: /circulation/renew-by-id
  From: https://s3.amazonaws.com/foliodocs/api/mod-circulation/circulation.html
  (Requires more parameters, both itemId and userId.)
  Consider: /circulation/renew-by-barcode
  From: https://s3.amazonaws.com/foliodocs/api/mod-circulation/circulation.html
  (Requires more parameters, both itemBarcode and userBarcode (there is a userBarcode?).)
  Consider: /patron/account/{id}
  From: https://s3.amazonaws.com/foliodocs/api/edge-patron/mod-patron-patron.html (that link may not work)

**Comment by wwelling** [comment]
Initial use by MyLibraryService, https://github.com/TAMULib/MyLibraryService/blob/master/src/main/java/edu/tamu/app/util/VoyagerUtility.java#L378

Should include the creation of a `Renewal` Catalog domain POJO. Consider renaming to the most appropriate library semantic.

Blocks #94

**Comment by wwelling** [comment]
https://s3.amazonaws.com/foliodocs/api/edge-patron/edge-patron.html#patron_account__id__item__itemid__renew_post
