### ISSUE TITLE
FOLIO implementation of renew all

### ISSUE THREAD

**Issue by jcreel** [TAMULib/CatalogService#94]
"/myrecord/renewall" (user)
  PUT
  Renew all charged items for some user.
  This is being renewed on a per-database basis for each/all databases.
  Does a POST to the URL.
  Such as: http://XXX/patron/YYY/circulationActions/loans?patron_homedb=ZZZ
  ---
  Consider: /patron/account/{id}/item/{itemId}/renew
  From: https://s3.amazonaws.com/foliodocs/api/edge-patron/edge-patron.html
  Consider: /patron/account/{id}/item/{itemId}/renew
  From: https://s3.amazonaws.com/foliodocs/api/edge-patron/mod-patron-patron.html

**Comment by wwelling** [comment]
Initial use by MyLibraryService, https://github.com/TAMULib/MyLibraryService/blob/master/src/main/java/edu/tamu/app/util/VoyagerUtility.java#L414

Should include the creation of a `Renewal` Catalog domain POJO. Consider renaming to the most appropriate library semantic.

**Comment by kaladay** [comment]
This is now expected to be handled by the client using loops as appropriate and is effectively solved by #93 .
