### ISSUE TITLE
FOLIO implementation of request cancellation

### ISSUE THREAD

**Issue by jcreel** [TAMULib/CatalogService#96]
"/myrecord/cancel" (href)
  PUT
  Renew a charged item.
  Does a DELETE to the provided URL.
  Such as: http://XXX/YYY
  ---
  Consider: /patron/account/{id}/hold/{holdId}/cancel
  From: https://s3.amazonaws.com/foliodocs/api/edge-patron/edge-patron.html
  This endpoint appears to set a canceledDate, so the record will be persisted after cancellation.
  Consider: /patron/account/{id}/hold/{holdId}/cancel
  From: https://s3.amazonaws.com/foliodocs/api/edge-patron/mod-patron-patron.html

**Comment by wwelling** [comment]
For  use by MyLibraryService https://github.com/TAMULib/MyLibraryService/blob/master/src/main/java/edu/tamu/app/util/VoyagerUtility.java#L533

**Comment by wwelling** [comment]
https://s3.amazonaws.com/foliodocs/api/edge-patron/edge-patron.html#patron_account__id__hold__holdid__cancel_post
